## Loading Data into Pandas

In [1]:
 import pandas as pd

In [2]:
df = pd.read_csv('Pokemon.csv') # For csv
#df = pd.read_excel('Pokemon.xlsx') #For Excel File xlsx

In [3]:
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [4]:
df.head(3)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False

In [5]:
df.tail(3)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

## Read Headers of Data

In [6]:
df.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'Total', 'HP', 'Attack', 'Defense',
       'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

## Read Each Column

In [7]:
df.Name

0                  Bulbasaur
1                    Ivysaur
2                   Venusaur
3      VenusaurMega Venusaur
4                 Charmander
               ...
795                  Diancie
796      DiancieMega Diancie
797      HoopaHoopa Confined
798       HoopaHoopa Unbound
799                Volcanion
Name: Name, Length: 800, dtype: object

In [8]:
df['Attack'][:5]

0     49
1     62
2     82
3    100
4     52
Name: Attack, dtype: int64

In [9]:
df['Type 2'][795:]

795    Fairy
796    Fairy
797    Ghost
798     Dark
799    Water
Name: Type 2, dtype: object

In [10]:
df[['Name','Attack']][4:14]

                         Name  Attack
4                  Charmander      52
5                  Charmeleon      64
6                   Charizard      84
7   CharizardMega Charizard X     130
8   CharizardMega Charizard Y     104
9                    Squirtle      48
10                  Wartortle      63
11                  Blastoise      83
12    BlastoiseMega Blastoise     103
13                   Caterpie      30

## Read Each Row

In [11]:
df.head(2)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False

In [12]:
df.iloc[1] #return record in second row index starts with 0

#                   2
Name          Ivysaur
Type 1          Grass
Type 2         Poison
Total             405
HP                 60
Attack             62
Defense            63
Sp. Atk            80
Sp. Def            80
Speed              60
Generation          1
Legendary       False
Name: 1, dtype: object

In [13]:
df.iloc[0:4]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False

In [57]:
# for index, row in df.iterrows():
#     print(index,row)

700 #                   639
Name          Terrakion
Type 1             Rock
Type 2         Fighting
Total               580
HP                   91
Attack              129
Defense              90
Sp. Atk              72
Sp. Def              90
Speed               108
Generation            5
Legendary          True
Name: 700, dtype: object
701 #                  640
Name          Virizion
Type 1           Grass
Type 2        Fighting
Total              580
HP                  91
Attack              90
Defense             72
Sp. Atk             90
Sp. Def            129
Speed              108
Generation           5
Legendary         True
Name: 701, dtype: object
702 #                                 641
Name          TornadusIncarnate Forme
Type 1                         Flying
Type 2                            NaN
Total                             580
HP                                 79
Attack                            115
Defense                            70
Sp. Atk                           125
Sp. Def                            80
Speed                             111
Generation                          5
Legendary                        True
Name: 702, dtype: object
703 #                               641
Name          TornadusTherian Forme
Type 1                       Flying
Type 2                          NaN
Total                           580
HP                               79
Attack                          100
Defense                          80
Sp. Atk                         110
Sp. Def                          90
Speed                           121
Generation                        5
Legendary                      True
Name: 703, dtype: object
704 #                                  642
Name          ThundurusIncarnate Forme
Type 1                        Electric
Type 2                          Flying
Total                              580
HP                                  79
Attack                             115
Defense                             70
Sp. Atk                            125
Sp. Def                             80
Speed                              111
Generation                           5
Legendary                         True
Name: 704, dtype: object
705 #                                642
Name          ThundurusTherian Forme
Type 1                      Electric
Type 2                        Flying
Total                            580
HP                                79
Attack                           105
Defense                           70
Sp. Atk                          145
Sp. Def                           80
Speed                            101
Generation                         5
Legendary                       True
Name: 705, dtype: object
706 #                  643
Name          Reshiram
Type 1          Dragon
Type 2            Fire
Total              680
HP                 100
Attack             120
Defense            100
Sp. Atk            150
Sp. Def            120
Speed               90
Generation           5
Legendary         True
Name: 706, dtype: object
707 #                  644
Name            Zekrom
Type 1          Dragon
Type 2        Electric
Total              680
HP                 100
Attack             150
Defense            120
Sp. Atk            120
Sp. Def            100
Speed               90
Generation           5
Legendary         True
Name: 707, dtype: object
708 #                                 645
Name          LandorusIncarnate Forme
Type 1                         Ground
Type 2                         Flying
Total                             600
HP                                 89
Attack                            125
Defense                            90
Sp. Atk                           115
Sp. Def                            80
Speed                             101
Generation                          5
Legendary                        True
Name: 708, dtype: object
709 #                               645
Name          LandorusTherian Forme
Type 1                       Ground
Type 2                       Flying
Total                           600
HP                               89
Attack                          145
Defense                          90
Sp. Atk                         105
Sp. Def                          80
Speed                            91
Generation                        5
Legendary                      True
Name: 709, dtype: object
710 #                646
Name          Kyurem
Type 1        Dragon
Type 2           Ice
Total            660
HP               125
Attack           130
Defense           90
Sp. Atk          130
Sp. Def           90
Speed             95
Generation         5
Legendary       True
Name: 710, dtype: object
711 #                            646
Name          KyuremBlack Kyurem
Type 1                    Dragon
Type 2                       Ice
Total                        700
HP                           125
Attack                       170
Defense                      100
Sp. Atk                      120
Sp. Def                       90
Speed                         95
Generation                     5
Legendary                   True
Name: 711, dtype: object
712 #                            646
Name          KyuremWhite Kyurem
Type 1                    Dragon
Type 2                       Ice
Total                        700
HP                           125
Attack                       120
Defense                       90
Sp. Atk                      170
Sp. Def                      100
Speed                         95
Generation                     5
Legendary                   True
Name: 712, dtype: object
713 #                              647
Name          KeldeoOrdinary Forme
Type 1                       Water
Type 2                    Fighting
Total                          580
HP                              91
Attack                          72
Defense                         90
Sp. Atk                        129
Sp. Def                         90
Speed                          108
Generation                       5
Legendary                    False
Name: 713, dtype: object
714 #                              647
Name          KeldeoResolute Forme
Type 1                       Water
Type 2                    Fighting
Total                          580
HP                              91
Attack                          72
Defense                         90
Sp. Atk                        129
Sp. Def                         90
Speed                          108
Generation                       5
Legendary                    False
Name: 714, dtype: object
715 #                            648
Name          MeloettaAria Forme
Type 1                    Normal
Type 2                   Psychic
Total                        600
HP                           100
Attack                        77
Defense                       77
Sp. Atk                      128
Sp. Def                      128
Speed                         90
Generation                     5
Legendary                  False
Name: 715, dtype: object
716 #                                 648
Name          MeloettaPirouette Forme
Type 1                         Normal
Type 2                       Fighting
Total                             600
HP                                100
Attack                            128
Defense                            90
Sp. Atk                            77
Sp. Def                            77
Speed                             128
Generation                          5
Legendary                       False
Name: 716, dtype: object
717 #                  649
Name          Genesect
Type 1             Bug
Type 2           Steel
Total              600
HP                  71
Attack             120
Defense             95
Sp. Atk            120
Sp. Def             95
Speed               99
Generation           5
Legendary        False
Name: 717, dtype: object
718 #                 650
Name          Chespin
Type 1          Grass
Type 2            NaN
Total             313
HP                 56
Attack             61
Defense            65
Sp. Atk            48
Sp. Def            45
Speed              38
Generation          6
Legendary       False
Name: 718, dtype: object
719 #                   651
Name          Quilladin
Type 1            Grass
Type 2              NaN
Total               405
HP                   61
Attack               78
Defense              95
Sp. Atk              56
Sp. Def              58
Speed                57
Generation            6
Legendary         False
Name: 719, dtype: object
720 #                    652
Name          Chesnaught
Type 1             Grass
Type 2          Fighting
Total                530
HP                    88
Attack               107
Defense              122
Sp. Atk               74
Sp. Def               75
Speed                 64
Generation             6
Legendary          False
Name: 720, dtype: object
721 #                  653
Name          Fennekin
Type 1            Fire
Type 2             NaN
Total              307
HP                  40
Attack              45
Defense             40
Sp. Atk             62
Sp. Def             60
Speed               60
Generation           6
Legendary        False
Name: 721, dtype: object
722 #                 654
Name          Braixen
Type 1           Fire
Type 2            NaN
Total             409
HP                 59
Attack             59
Defense            58
Sp. Atk            90
Sp. Def            70
Speed              73
Generation          6
Legendary       False
Name: 722, dtype: object
723 #                 655
Name          Delphox
Type 1           Fire
Type 2        Psychic
Total             534
HP                 75
Attack             69
Defense            72
Sp. Atk           114
Sp. Def           100
Speed             104
Generation          6
Legendary       False
Name: 723, dtype: object
724 #                 656
Name          Froakie
Type 1          Water
Type 2            NaN
Total             314
HP                 41
Attack             56
Defense            40
Sp. Atk            62
Sp. Def            44
Speed              71
Generation          6
Legendary       False
Name: 724, dtype: object
725 #                   657
Name          Frogadier
Type 1            Water
Type 2              NaN
Total               405
HP                   54
Attack               63
Defense              52
Sp. Atk              83
Sp. Def              56
Speed                97
Generation            6
Legendary         False
Name: 725, dtype: object
726 #                  658
Name          Greninja
Type 1           Water
Type 2            Dark
Total              530
HP                  72
Attack              95
Defense             67
Sp. Atk            103
Sp. Def             71
Speed              122
Generation           6
Legendary        False
Name: 726, dtype: object
727 #                  659
Name          Bunnelby
Type 1          Normal
Type 2             NaN
Total              237
HP                  38
Attack              36
Defense             38
Sp. Atk             32
Sp. Def             36
Speed               57
Generation           6
Legendary        False
Name: 727, dtype: object
728 #                   660
Name          Diggersby
Type 1           Normal
Type 2           Ground
Total               423
HP                   85
Attack               56
Defense              77
Sp. Atk              50
Sp. Def              77
Speed                78
Generation            6
Legendary         False
Name: 728, dtype: object
729 #                    661
Name          Fletchling
Type 1            Normal
Type 2            Flying
Total                278
HP                    45
Attack                50
Defense               43
Sp. Atk               40
Sp. Def               38
Speed                 62
Generation             6
Legendary          False
Name: 729, dtype: object
730 #                     662
Name          Fletchinder
Type 1               Fire
Type 2             Flying
Total                 382
HP                     62
Attack                 73
Defense                55
Sp. Atk                56
Sp. Def                52
Speed                  84
Generation              6
Legendary           False
Name: 730, dtype: object
731 #                    663
Name          Talonflame
Type 1              Fire
Type 2            Flying
Total                499
HP                    78
Attack                81
Defense               71
Sp. Atk               74
Sp. Def               69
Speed                126
Generation             6
Legendary          False
Name: 731, dtype: object
732 #                    664
Name          Scatterbug
Type 1               Bug
Type 2               NaN
Total                200
HP                    38
Attack                35
Defense               40
Sp. Atk               27
Sp. Def               25
Speed                 35
Generation             6
Legendary          False
Name: 732, dtype: object
733 #                665
Name          Spewpa
Type 1           Bug
Type 2           NaN
Total            213
HP                45
Attack            22
Defense           60
Sp. Atk           27
Sp. Def           30
Speed             29
Generation         6
Legendary      False
Name: 733, dtype: object
734 #                  666
Name          Vivillon
Type 1             Bug
Type 2          Flying
Total              411
HP                  80
Attack              52
Defense             50
Sp. Atk             90
Sp. Def             50
Speed               89
Generation           6
Legendary        False
Name: 734, dtype: object
735 #                667
Name          Litleo
Type 1          Fire
Type 2        Normal
Total            369
HP                62
Attack            50
Defense           58
Sp. Atk           73
Sp. Def           54
Speed             72
Generation         6
Legendary      False
Name: 735, dtype: object
736 #                668
Name          Pyroar
Type 1          Fire
Type 2        Normal
Total            507
HP                86
Attack            68
Defense           72
Sp. Atk          109
Sp. Def           66
Speed            106
Generation         6
Legendary      False
Name: 736, dtype: object
737 #                 669
Name          FlabÃ©bÃ©
Type 1          Fairy
Type 2            NaN
Total             303
HP                 44
Attack             38
Defense            39
Sp. Atk            61
Sp. Def            79
Speed              42
Generation          6
Legendary       False
Name: 737, dtype: object
738 #                 670
Name          Floette
Type 1          Fairy
Type 2            NaN
Total             371
HP                 54
Attack             45
Defense            47
Sp. Atk            75
Sp. Def            98
Speed              52
Generation          6
Legendary       False
Name: 738, dtype: object
739 #                 671
Name          Florges
Type 1          Fairy
Type 2            NaN
Total             552
HP                 78
Attack             65
Defense            68
Sp. Atk           112
Sp. Def           154
Speed              75
Generation          6
Legendary       False
Name: 739, dtype: object
740 #                672
Name          Skiddo
Type 1         Grass
Type 2           NaN
Total            350
HP                66
Attack            65
Defense           48
Sp. Atk           62
Sp. Def           57
Speed             52
Generation         6
Legendary      False
Name: 740, dtype: object
741 #                673
Name          Gogoat
Type 1         Grass
Type 2           NaN
Total            531
HP               123
Attack           100
Defense           62
Sp. Atk           97
Sp. Def           81
Speed             68
Generation         6
Legendary      False
Name: 741, dtype: object
742 #                  674
Name           Pancham
Type 1        Fighting
Type 2             NaN
Total              348
HP                  67
Attack              82
Defense             62
Sp. Atk             46
Sp. Def             48
Speed               43
Generation           6
Legendary        False
Name: 742, dtype: object
743 #                  675
Name           Pangoro
Type 1        Fighting
Type 2            Dark
Total              495
HP                  95
Attack             124
Defense             78
Sp. Atk             69
Sp. Def             71
Speed               58
Generation           6
Legendary        False
Name: 743, dtype: object
744 #                 676
Name          Furfrou
Type 1         Normal
Type 2            NaN
Total             472
HP                 75
Attack             80
Defense            60
Sp. Atk            65
Sp. Def            90
Speed             102
Generation          6
Legendary       False
Name: 744, dtype: object
745 #                 677
Name           Espurr
Type 1        Psychic
Type 2            NaN
Total             355
HP                 62
Attack             48
Defense            54
Sp. Atk            63
Sp. Def            60
Speed              68
Generation          6
Legendary       False
Name: 745, dtype: object
746 #                      678
Name          MeowsticMale
Type 1             Psychic
Type 2                 NaN
Total                  466
HP                      74
Attack                  48
Defense                 76
Sp. Atk                 83
Sp. Def                 81
Speed                  104
Generation               6
Legendary            False
Name: 746, dtype: object
747 #                        678
Name          MeowsticFemale
Type 1               Psychic
Type 2                   NaN
Total                    466
HP                        74
Attack                    48
Defense                   76
Sp. Atk                   83
Sp. Def                   81
Speed                    104
Generation                 6
Legendary              False
Name: 747, dtype: object
748 #                 679
Name          Honedge
Type 1          Steel
Type 2          Ghost
Total             325
HP                 45
Attack             80
Defense           100
Sp. Atk            35
Sp. Def            37
Speed              28
Generation          6
Legendary       False
Name: 748, dtype: object
749 #                  680
Name          Doublade
Type 1           Steel
Type 2           Ghost
Total              448
HP                  59
Attack             110
Defense            150
Sp. Atk             45
Sp. Def             49
Speed               35
Generation           6
Legendary        False
Name: 749, dtype: object
750 #                              681
Name          AegislashBlade Forme
Type 1                       Steel
Type 2                       Ghost
Total                          520
HP                              60
Attack                         150
Defense                         50
Sp. Atk                        150
Sp. Def                         50
Speed                           60
Generation                       6
Legendary                    False
Name: 750, dtype: object
751 #                               681
Name          AegislashShield Forme
Type 1                        Steel
Type 2                        Ghost
Total                           520
HP                               60
Attack                           50
Defense                         150
Sp. Atk                          50
Sp. Def                         150
Speed                            60
Generation                        6
Legendary                     False
Name: 751, dtype: object
752 #                  682
Name          Spritzee
Type 1           Fairy
Type 2             NaN
Total              341
HP                  78
Attack              52
Defense             60
Sp. Atk             63
Sp. Def             65
Speed               23
Generation           6
Legendary        False
Name: 752, dtype: object
753 #                    683
Name          Aromatisse
Type 1             Fairy
Type 2               NaN
Total                462
HP                   101
Attack                72
Defense               72
Sp. Atk               99

In [15]:
# for index, row in df.iterrows():
#     print(index,row['Name'])

0 Bulbasaur
1 Ivysaur
2 Venusaur
3 VenusaurMega Venusaur
4 Charmander
5 Charmeleon
6 Charizard
7 CharizardMega Charizard X
8 CharizardMega Charizard Y
9 Squirtle
10 Wartortle
11 Blastoise
12 BlastoiseMega Blastoise
13 Caterpie
14 Metapod
15 Butterfree
16 Weedle
17 Kakuna
18 Beedrill
19 BeedrillMega Beedrill
20 Pidgey
21 Pidgeotto
22 Pidgeot
23 PidgeotMega Pidgeot
24 Rattata
25 Raticate
26 Spearow
27 Fearow
28 Ekans
29 Arbok
30 Pikachu
31 Raichu
32 Sandshrew
33 Sandslash
34 Nidoranâ™€
35 Nidorina
36 Nidoqueen
37 Nidoranâ™‚
38 Nidorino
39 Nidoking
40 Clefairy
41 Clefable
42 Vulpix
43 Ninetales
44 Jigglypuff
45 Wigglytuff
46 Zubat
47 Golbat
48 Oddish
49 Gloom
50 Vileplume
51 Paras
52 Parasect
53 Venonat
54 Venomoth
55 Diglett
56 Dugtrio
57 Meowth
58 Persian
59 Psyduck
60 Golduck
61 Mankey
62 Primeape
63 Growlithe
64 Arcanine
65 Poliwag
66 Poliwhirl
67 Poliwrath
68 Abra
69 Kadabra
70 Alakazam
71 AlakazamMega Alakazam
72 Machop
73 Machoke
74 Machamp
75 Bellsprout
76 Weepinbell
77 Victreebel
78 Tentacool
79 Tentacruel
80 Geodude
81 Graveler
82 Golem
83 Ponyta
84 Rapidash
85 Slowpoke
86 Slowbro
87 SlowbroMega Slowbro
88 Magnemite
89 Magneton
90 Farfetch'd
91 Doduo
92 Dodrio
93 Seel
94 Dewgong
95 Grimer
96 Muk
97 Shellder
98 Cloyster
99 Gastly
100 Haunter
101 Gengar
102 GengarMega Gengar
103 Onix
104 Drowzee
105 Hypno
106 Krabby
107 Kingler
108 Voltorb
109 Electrode
110 Exeggcute
111 Exeggutor
112 Cubone
113 Marowak
114 Hitmonlee
115 Hitmonchan
116 Lickitung
117 Koffing
118 Weezing
119 Rhyhorn
120 Rhydon
121 Chansey
122 Tangela
123 Kangaskhan
124 KangaskhanMega Kangaskhan
125 Horsea
126 Seadra
127 Goldeen
128 Seaking
129 Staryu
130 Starmie
131 Mr. Mime
132 Scyther
133 Jynx
134 Electabuzz
135 Magmar
136 Pinsir
137 PinsirMega Pinsir
138 Tauros
139 Magikarp
140 Gyarados
141 GyaradosMega Gyarados
142 Lapras
143 Ditto
144 Eevee
145 Vaporeon
146 Jolteon
147 Flareon
148 Porygon
149 Omanyte
150 Omastar
151 Kabuto
152 Kabutops
153 Aerodactyl
154 AerodactylMega Aerodactyl
155 Snorlax
156 Articuno
157 Zapdos
158 Moltres
159 Dratini
160 Dragonair
161 Dragonite
162 Mewtwo
163 MewtwoMega Mewtwo X
164 MewtwoMega Mewtwo Y
165 Mew
166 Chikorita
167 Bayleef
168 Meganium
169 Cyndaquil
170 Quilava
171 Typhlosion
172 Totodile
173 Croconaw
174 Feraligatr
175 Sentret
176 Furret
177 Hoothoot
178 Noctowl
179 Ledyba
180 Ledian
181 Spinarak
182 Ariados
183 Crobat
184 Chinchou
185 Lanturn
186 Pichu
187 Cleffa
188 Igglybuff
189 Togepi
190 Togetic
191 Natu
192 Xatu
193 Mareep
194 Flaaffy
195 Ampharos
196 AmpharosMega Ampharos
197 Bellossom
198 Marill
199 Azumarill
200 Sudowoodo
201 Politoed
202 Hoppip
203 Skiploom
204 Jumpluff
205 Aipom
206 Sunkern
207 Sunflora
208 Yanma
209 Wooper
210 Quagsire
211 Espeon
212 Umbreon
213 Murkrow
214 Slowking
215 Misdreavus
216 Unown
217 Wobbuffet
218 Girafarig
219 Pineco
220 Forretress
221 Dunsparce
222 Gligar
223 Steelix
224 SteelixMega Steelix
225 Snubbull
226 Granbull
227 Qwilfish
228 Scizor
229 ScizorMega Scizor
230 Shuckle
231 Heracross
232 HeracrossMega Heracross
233 Sneasel
234 Teddiursa
235 Ursaring
236 Slugma
237 Magcargo
238 Swinub
239 Piloswine
240 Corsola
241 Remoraid
242 Octillery
243 Delibird
244 Mantine
245 Skarmory
246 Houndour
247 Houndoom
248 HoundoomMega Houndoom
249 Kingdra
250 Phanpy
251 Donphan
252 Porygon2
253 Stantler
254 Smeargle
255 Tyrogue
256 Hitmontop
257 Smoochum
258 Elekid
259 Magby
260 Miltank
261 Blissey
262 Raikou
263 Entei
264 Suicune
265 Larvitar
266 Pupitar
267 Tyranitar
268 TyranitarMega Tyranitar
269 Lugia
270 Ho-oh
271 Celebi
272 Treecko
273 Grovyle
274 Sceptile
275 SceptileMega Sceptile
276 Torchic
277 Combusken
278 Blaziken
279 BlazikenMega Blaziken
280 Mudkip
281 Marshtomp
282 Swampert
283 SwampertMega Swampert
284 Poochyena
285 Mightyena
286 Zigzagoon
287 Linoone
288 Wurmple
289 Silcoon
290 Beautifly
291 Cascoon
292 Dustox
293 Lotad
294 Lombre
295 Ludicolo
296 Seedot
297 Nuzleaf
298 Shiftry
299 Taillow
300 Swellow
301 Wingull
302 Pelipper
303 Ralts
304 Kirlia
305 Gardevoir
306 GardevoirMega Gardevoir
307 Surskit
308 Masquerain
309 Shroomish
310 Breloom
311 Slakoth
312 Vigoroth
313 Slaking
314 Nincada
315 Ninjask
316 Shedinja
317 Whismur
318 Loudred
319 Exploud
320 Makuhita
321 Hariyama
322 Azurill
323 Nosepass
324 Skitty
325 Delcatty
326 Sableye
327 SableyeMega Sableye
328 Mawile
329 MawileMega Mawile
330 Aron
331 Lairon
332 Aggron
333 AggronMega Aggron
334 Meditite
335 Medicham
336 MedichamMega Medicham
337 Electrike
338 Manectric
339 ManectricMega Manectric
340 Plusle
341 Minun
342 Volbeat
343 Illumise
344 Roselia
345 Gulpin
346 Swalot
347 Carvanha
348 Sharpedo
349 SharpedoMega Sharpedo
350 Wailmer
351 Wailord
352 Numel
353 Camerupt
354 CameruptMega Camerupt
355 Torkoal
356 Spoink
357 Grumpig
358 Spinda
359 Trapinch
360 Vibrava
361 Flygon
362 Cacnea
363 Cacturne
364 Swablu
365 Altaria
366 AltariaMega Altaria
367 Zangoose
368 Seviper
369 Lunatone
370 Solrock
371 Barboach
372 Whiscash
373 Corphish
374 Crawdaunt
375 Baltoy
376 Claydol
377 Lileep
378 Cradily
379 Anorith
380 Armaldo
381 Feebas
382 Milotic
383 Castform
384 Kecleon
385 Shuppet
386 Banette
387 BanetteMega Banette
388 Duskull
389 Dusclops
390 Tropius
391 Chimecho
392 Absol
393 AbsolMega Absol
394 Wynaut
395 Snorunt
396 Glalie
397 GlalieMega Glalie
398 Spheal
399 Sealeo
400 Walrein
401 Clamperl
402 Huntail
403 Gorebyss
404 Relicanth
405 Luvdisc
406 Bagon
407 Shelgon
408 Salamence
409 SalamenceMega Salamence
410 Beldum
411 Metang
412 Metagross
413 MetagrossMega Metagross
414 Regirock
415 Regice
416 Registeel
417 Latias
418 LatiasMega Latias
419 Latios
420 LatiosMega Latios
421 Kyogre
422 KyogrePrimal Kyogre
423 Groudon
424 GroudonPrimal Groudon
425 Rayquaza
426 RayquazaMega Rayquaza
427 Jirachi
428 DeoxysNormal Forme
429 DeoxysAttack Forme
430 DeoxysDefense Forme
431 DeoxysSpeed Forme
432 Turtwig
433 Grotle
434 Torterra
435 Chimchar
436 Monferno
437 Infernape
438 Piplup
439 Prinplup
440 Empoleon
441 Starly
442 Staravia
443 Staraptor
444 Bidoof
445 Bibarel
446 Kricketot
447 Kricketune
448 Shinx
449 Luxio
450 Luxray
451 Budew
452 Roserade
453 Cranidos
454 Rampardos
455 Shieldon
456 Bastiodon
457 Burmy
458 WormadamPlant Cloak
459 WormadamSandy Cloak
460 WormadamTrash Cloak
461 Mothim
462 Combee
463 Vespiquen
464 Pachirisu
465 Buizel
466 Floatzel
467 Cherubi
468 Cherrim
469 Shellos
470 Gastrodon
471 Ambipom
472 Drifloon
473 Drifblim
474 Buneary
475 Lopunny
476 LopunnyMega Lopunny
477 Mismagius
478 Honchkrow
479 Glameow
480 Purugly
481 Chingling
482 Stunky
483 Skuntank
484 Bronzor
485 Bronzong
486 Bonsly
487 Mime Jr.
488 Happiny
489 Chatot
490 Spiritomb
491 Gible
492 Gabite
493 Garchomp
494 GarchompMega Garchomp
495 Munchlax
496 Riolu
497 Lucario
498 LucarioMega Lucario
499 Hippopotas
500 Hippowdon
501 Skorupi
502 Drapion
503 Croagunk
504 Toxicroak
505 Carnivine
506 Finneon
507 Lumineon
508 Mantyke
509 Snover
510 Abomasnow
511 AbomasnowMega Abomasnow
512 Weavile
513 Magnezone
514 Lickilicky
515 Rhyperior
516 Tangrowth
517 Electivire
518 Magmortar
519 Togekiss
520 Yanmega
521 Leafeon
522 Glaceon
523 Gliscor
524 Mamoswine
525 Porygon-Z
526 Gallade
527 GalladeMega Gallade
528 Probopass
529 Dusknoir
530 Froslass
531 Rotom
532 RotomHeat Rotom
533 RotomWash Rotom
534 RotomFrost Rotom
535 RotomFan Rotom
536 RotomMow Rotom
537 Uxie
538 Mesprit
539 Azelf
540 Dialga
541 Palkia
542 Heatran
543 Regigigas
544 GiratinaAltered Forme
545 GiratinaOrigin Forme
546 Cresselia
547 Phione
548 Manaphy
549 Darkrai
550 ShayminLand Forme
551 ShayminSky Forme
552 Arceus
553 Victini
554 Snivy
555 Servine
556 Serperior
557 Tepig
558 Pignite
559 Emboar
560 Oshawott
561 Dewott
562 Samurott
563 Patrat
564 Watchog
565 Lillipup
566 Herdier
567 Stoutland
568 Purrloin
569 Liepard
570 Pansage
571 Simisage
572 Pansear
573 Simisear
574 Panpour
575 Simipour
576 Munna
577 Musharna
578 Pidove
579 Tranquill
580 Unfezant
581 Blitzle
582 Zebstrika
583 Roggenrola
584 Boldore
585 Gigalith
586 Woobat
587 Swoobat
588 Drilbur
589 Excadrill
590 Audino
591 AudinoMega Audino
592 Timburr
593 Gurdurr
594 Conkeldurr
595 Tympole
596 Palpitoad
597 Seismitoad
598 Throh
599 Sawk
600 Sewaddle
601 Swadloon
602 Leavanny
603 Venipede
604 Whirlipede
605 Scolipede
606 Cottonee
607 Whimsicott
608 Petilil
609 Lilligant
610 Basculin
611 Sandile
612 Krokorok
613 Krookodile
614 Darumaka
615 DarmanitanStandard Mode
616 DarmanitanZen Mode
617 Maractus
618 Dwebble
619 Crustle
620 Scraggy
621 Scrafty
622 Sigilyph
623 Yamask
624 Cofagrigus
625 Tirtouga
626 Carracosta
627 Archen
628 Archeops
629 Trubbish
630 Garbodor
631 Zorua
632 Zoroark
633 Minccino
634 Cinccino
635 Gothita
636 Gothorita
637 Gothitelle
638 Solosis
639 Duosion
640 Reuniclus
641 Ducklett
642 Swanna
643 Vanillite
644 Vanillish
645 Vanilluxe
646 Deerling
647 Sawsbuck
648 Emolga
649 Karrablast
650 Escavalier
651 Foongus
652 Amoonguss
653 Frillish
654 Jellicent
655 Alomomola
656 Joltik
657 Galvantula
658 Ferroseed
659 Ferrothorn
660 Klink
661 Klang
662 Klinklang
663 Tynamo
664 Eelektrik
665 Eelektross
666 Elgyem
667 Beheeyem
668 Litwick
669 Lampent
670 Chandelure
671 Axew
672 Fraxure
673 Haxorus
674 Cubchoo
675 Beartic
676 Cryogonal
677 Shelmet
678 Accelgor
679 Stunfisk
680 Mienfoo
681 Mienshao
682 Druddigon
683 Golett
684 Golurk
685 Pawniard
686 Bisharp
687 Bouffalant
688 Rufflet
689 Braviary
690 Vullaby
691 Mandibuzz
692 Heatmor
693 Durant
694 Deino
695 Zweilous
696 Hydreigon
697 Larvesta
698 Volcarona
699 Cobalion
700 Terrakion
701 Virizion
702 TornadusIncarnate Forme
703 TornadusTherian Forme
704 ThundurusIncarnate Forme
705 ThundurusTherian Forme
706 Reshiram
707 Zekrom
708 LandorusIncarnate Forme
709 LandorusTherian Forme
710 Kyurem
711 KyuremBlack Kyurem
712 KyuremWhite Kyurem
713 KeldeoOrdinary Forme
714 KeldeoResolute Forme
715 MeloettaAria Forme
716 MeloettaPirouette Forme
717 Genesect
718 Chespin
719 Quilladin
720 Chesnaught
721 Fennekin
722 Braixen
723 Delphox
724 Froakie
725 Frogadier
726 Greninja
727 Bunnelby
728 Diggersby
729 Fletchling
730 Fletchinder
731 Talonflame
732 Scatterbug
733 Spewpa
734 Vivillon
735 Litleo
736 Pyroar
737 FlabÃ©bÃ©
738 Floette
739 Florges
740 Skiddo
741 Gogoat
742 Pancham
743 Pangoro
744 Furfrou
745 Espurr
746 MeowsticMale
747 MeowsticFemale
748 Honedge
749 Doublade
750 AegislashBlade Forme
751 AegislashShield Forme
752 Spritzee
753 Aromatisse
754 Swirlix
755 Slurpuff
756 Inkay
757 Malamar
758 Binacle
759 Barbaracle
760 Skrelp
761 Dragalge
762 Clauncher
763 Clawitzer
764 Helioptile
765 Heliolisk
766 Tyrunt
767 Tyrantrum
768 Amaura
769 Aurorus
770 Sylveon
771 Hawlucha
772 Dedenne
773 Carbink
774 Goomy
775 Sliggoo
776 Goodra
777 Klefki
778 Phantump
779 Trevenant
780 PumpkabooAverage Size
781 PumpkabooSmall Size
782 PumpkabooLarge Size
783 PumpkabooSuper Size
784 GourgeistAverage Size
785 GourgeistSmall Size
786 GourgeistLarge Size
787 GourgeistSuper Size
788 Bergmite
789 Avalugg
790 Noibat
791 Noivern
792 Xerneas
793 Yveltal
794 Zygarde50% Forme
795 Diancie
796 DiancieMega Diancie
797 HoopaHoopa Confined
798 HoopaHoopa Unbound
799 Volcanion

## Read specific Location

In [16]:
df.iloc[2,1]

'Venusaur'

In [17]:
df.head(1)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False

In [18]:
df.loc[df['Type 1'] == "Grass"]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
48,43,Oddish,Grass,Poison,320,45,50,55,75,65,30,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
718,650,Chespin,Grass,NaN,313,56,61,65,48,45,38,6,False
719,651,Quilladin,Grass,NaN,405,61,78,95,56,58,57,6,False
720,652,Chesnaught,Grass,Fighting,530,88,107,122,74,75,64,6,False
740,672,Skiddo,Grass,NaN,350,66,65,48,62,57,52,6,False
741,673,Gogoat,Grass,NaN,531,123,100,62,97,81,68,6,False

In [19]:
df['Type 1'] == "Grass"

0       True
1       True
2       True
3       True
4      False
       ...
795    False
796    False
797    False
798    False
799    False
Name: Type 1, Length: 800, dtype: bool

## Sorting/Describing Data

In [20]:
df.describe()

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.00000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,435.10250,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,119.96304,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,180.00000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,330.00000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,450.00000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,515.00000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,780.00000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

In [21]:
df.sort_values('Name')

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
510,460,Abomasnow,Grass,Ice,494,90,92,75,92,85,60,4,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,594,90,132,105,132,105,30,4,False
68,63,Abra,Psychic,NaN,310,25,20,15,105,55,90,1,False
392,359,Absol,Dark,NaN,465,65,130,60,75,60,75,3,False
393,359,AbsolMega Absol,Dark,NaN,565,65,150,60,115,60,115,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
632,571,Zoroark,Dark,NaN,510,60,105,60,120,60,105,5,False
631,570,Zorua,Dark,NaN,330,40,65,40,80,40,65,5,False
46,41,Zubat,Poison,Flying,245,40,45,35,30,40,55,1,False
695,634,Zweilous,Dark,Dragon,420,72,85,70,65,70,58,5,False
794,718,Zygarde50% Forme,Dragon,Ground,600,108,100,121,81,95,95,6,True

In [22]:
df.sort_values(['Type 1','HP'], ascending = [1,0])

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
520,469,Yanmega,Bug,Flying,515,86,76,86,116,56,95,4,False
698,637,Volcarona,Bug,Fire,550,85,60,65,135,105,100,5,False
231,214,Heracross,Bug,Fighting,500,80,125,75,40,95,85,2,False
232,214,HeracrossMega Heracross,Bug,Fighting,600,80,185,115,40,105,75,2,False
678,617,Accelgor,Bug,NaN,495,80,70,40,100,60,145,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,98,Krabby,Water,NaN,325,30,105,90,25,25,50,1,False
125,116,Horsea,Water,NaN,295,30,40,70,70,25,60,1,False
129,120,Staryu,Water,NaN,340,30,45,55,70,55,85,1,False
139,129,Magikarp,Water,NaN,200,20,10,55,15,20,80,1,False
381,349,Feebas,Water,NaN,200,20,15,20,10,55,80,3,False

## Make changes to data

In [23]:
df['Total'] = df['HP'] + df['Defense'] + df['Attack'] + df['Sp. Atk']+ df['Sp. Def'] + df['Speed']

In [24]:
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [25]:
df.drop(columns = ['Total'], inplace = True)
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [26]:
df['Total'] = df.iloc[:,4:10].sum(axis = 1)
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,600
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,700
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,600
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,680
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,600

In [27]:
cols = list(df.columns)

In [28]:
cols

['#',
 'Name',
 'Type 1',
 'Type 2',
 'HP',
 'Attack',
 'Defense',
 'Sp. Atk',
 'Sp. Def',
 'Speed',
 'Generation',
 'Legendary',
 'Total']

In [29]:
df = df[cols[0:4]+[cols[-1]]+cols[4:12]]

In [30]:
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [31]:
df.to_csv('modified_pokemon.csv', index = False)

## Filtering Data

In [32]:
df.loc[df['Type 1']=='Grass']

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
48,43,Oddish,Grass,Poison,320,45,50,55,75,65,30,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
718,650,Chespin,Grass,NaN,313,56,61,65,48,45,38,6,False
719,651,Quilladin,Grass,NaN,405,61,78,95,56,58,57,6,False
720,652,Chesnaught,Grass,Fighting,530,88,107,122,74,75,64,6,False
740,672,Skiddo,Grass,NaN,350,66,65,48,62,57,52,6,False
741,673,Gogoat,Grass,NaN,531,123,100,62,97,81,68,6,False

In [33]:
df[(df['Type 1']=='Grass') & ((df['Type 2'] == 'Poison') | (df['Total'] > 555))]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
48,43,Oddish,Grass,Poison,320,45,50,55,75,65,30,1,False
49,44,Gloom,Grass,Poison,395,60,65,70,85,75,40,1,False
50,45,Vileplume,Grass,Poison,490,75,80,85,110,90,50,1,False
75,69,Bellsprout,Grass,Poison,300,50,75,35,70,30,40,1,False
76,70,Weepinbell,Grass,Poison,390,65,90,50,85,45,55,1,False
77,71,Victreebel,Grass,Poison,490,80,105,65,100,70,70,1,False
275,254,SceptileMega Sceptile,Grass,Dragon,630,70,110,75,145,85,145,3,False
344,315,Roselia,Grass,Poison,400,50,60,45,100,80,65,3,False
451,406,Budew,Grass,Poison,280,40,30,35,50,70,55,4,False
452,407,Roserade,Grass,Poison,515,60,70,65,125,105,90,4,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,594,90,132,105,132,105,30,4,False
550,492,ShayminLand Forme,Grass,NaN,600,100,100,100,100,100,100,4,True
551,492,ShayminSky Forme,Grass,Flying,600,100,103,75,120,75,127,4,True
651,590,Foongus,Grass,Poison,294,69,55,45,55,55,15,5,False
652,591,Amoonguss,Grass,Poison,464,114,85,70,85,80,30,5,False
701,640,Virizion,Grass,Fighting,580,91,90,72,90,129,108,5,True

In [34]:
new_df = df[(df['Type 1']=='Grass') & ((df['Type 2'] == 'Poison') | (df['Total'] > 555))]

In [35]:
new_df = new_df.reset_index(drop = True)
new_df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,43,Oddish,Grass,Poison,320,45,50,55,75,65,30,1,False
5,44,Gloom,Grass,Poison,395,60,65,70,85,75,40,1,False
6,45,Vileplume,Grass,Poison,490,75,80,85,110,90,50,1,False
7,69,Bellsprout,Grass,Poison,300,50,75,35,70,30,40,1,False
8,70,Weepinbell,Grass,Poison,390,65,90,50,85,45,55,1,False
9,71,Victreebel,Grass,Poison,490,80,105,65,100,70,70,1,False
10,254,SceptileMega Sceptile,Grass,Dragon,630,70,110,75,145,85,145,3,False
11,315,Roselia,Grass,Poison,400,50,60,45,100,80,65,3,False
12,406,Budew,Grass,Poison,280,40,30,35,50,70,55,4,False
13,407,Roserade,Grass,Poison,515,60,70,65,125,105,90,4,False
14,460,AbomasnowMega Abomasnow,Grass,Ice,594,90,132,105,132,105,30,4,False
15,492,ShayminLand Forme,Grass,NaN,600,100,100,100,100,100,100,4,True
16,492,ShayminSky Forme,Grass,Flying,600,100,103,75,120,75,127,4,True
17,590,Foongus,Grass,Poison,294,69,55,45,55,55,15,5,False
18,591,Amoonguss,Grass,Poison,464,114,85,70,85,80,30,5,False
19,640,Virizion,Grass,Fighting,580,91,90,72,90,129,108,5,True

In [36]:
df.loc[df['Name'].str.contains('Mega')]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
12,9,BlastoiseMega Blastoise,Water,NaN,630,79,103,120,135,115,78,1,False
19,15,BeedrillMega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False
23,18,PidgeotMega Pidgeot,Normal,Flying,579,83,80,80,135,80,121,1,False
71,65,AlakazamMega Alakazam,Psychic,NaN,590,55,50,65,175,95,150,1,False
87,80,SlowbroMega Slowbro,Water,Psychic,590,95,75,180,130,80,30,1,False
102,94,GengarMega Gengar,Ghost,Poison,600,60,65,80,170,95,130,1,False
124,115,KangaskhanMega Kangaskhan,Normal,NaN,590,105,125,100,60,100,100,1,False
137,127,PinsirMega Pinsir,Bug,Flying,600,65,155,120,65,90,105,1,False
141,130,GyaradosMega Gyarados,Water,Dark,640,95,155,109,70,130,81,1,False
154,142,AerodactylMega Aerodactyl,Rock,Flying,615,80,135,85,70,95,150,1,False
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,780,106,190,100,154,100,130,1,True
164,150,MewtwoMega Mewtwo Y,Psychic,NaN,780,106,150,70,194,120,140,1,True
168,154,Meganium,Grass,NaN,525,80,82,100,83,100,80,2,False
196,181,AmpharosMega Ampharos,Electric,Dragon,610,90,95,105,165,110,45,2,False
224,208,SteelixMega Steelix,Steel,Ground,610,75,125,230,55,95,30,2,False
229,212,ScizorMega Scizor,Bug,Steel,600,70,150,140,65,100,75,2,False
232,214,HeracrossMega Heracross,Bug,Fighting,600,80,185,115,40,105,75,2,False
248,229,HoundoomMega Houndoom,Dark,Fire,600,75,90,90,140,90,115,2,False
268,248,TyranitarMega Tyranitar,Rock,Dark,700,100,164,150,95,120,71,2,False
275,254,SceptileMega Sceptile,Grass,Dragon,630,70,110,75,145,85,145,3,False
279,257,BlazikenMega Blaziken,Fire,Fighting,630,80,160,80,130,80,100,3,False
283,260,SwampertMega Swampert,Water,Ground,635,100,150,110,95,110,70,3,False
306,282,GardevoirMega Gardevoir,Psychic,Fairy,618,68,85,65,165,135,100,3,False
327,302,SableyeMega Sableye,Dark,Ghost,480,50,85,125,85,115,20,3,False
329,303,MawileMega Mawile,Steel,Fairy,480,50,105,125,55,95,50,3,False
333,306,AggronMega Aggron,Steel,NaN,630,70,140,230,60,80,50,3,False
336,308,MedichamMega Medicham,Fighting,Psychic,510,60,100,85,80,85,100,3,False
339,310,ManectricMega Manectric,Electric,NaN,575,70,75,80,135,80,135,3,False
349,319,SharpedoMega Sharpedo,Water,Dark,560,70,140,70,110,65,105,3,False
354,323,CameruptMega Camerupt,Fire,Ground,560,70,120,100,145,105,20,3,False
366,334,AltariaMega Altaria,Dragon,Fairy,590,75,110,110,110,105,80,3,False
387,354,BanetteMega Banette,Ghost,NaN,555,64,165,75,93,83,75,3,False
393,359,AbsolMega Absol,Dark,NaN,565,65,150,60,115,60,115,3,False
397,362,GlalieMega Glalie,Ice,NaN,580,80,120,80,120,80,100,3,False
409,373,SalamenceMega Salamence,Dragon,Flying,700,95,145,130,120,90,120,3,False
413,376,MetagrossMega Metagross,Steel,Psychic,700,80,145,150,105,110,110,3,False
418,380,LatiasMega Latias,Dragon,Psychic,700,80,100,120,140,150,110,3,True
420,381,LatiosMega Latios,Dragon,Psychic,700,80,130,100,160,120,110,3,True
426,384,RayquazaMega Rayquaza,Dragon,Flying,780,105,180,100,180,100,115,3,True
476,428,LopunnyMega Lopunny,Normal,Fighting,580,65,136,94,54,96,135,4,False
494,445,GarchompMega Garchomp,Dragon,Ground,700,108,170,115,120,95,92,4,False
498,448,LucarioMega Lucario,Fighting,Steel,625,70,145,88,140,70,112,4,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,594,90,132,105,132,105,30,4,False
527,475,GalladeMega Gallade,Psychic,Fighting,618,68,165,95,65,115,110,4,False
591,531,AudinoMega Audino,Normal,Fairy,545,103,60,126,80,126,50,5,False
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True

In [37]:
df.loc[~df['Name'].str.contains('Mega')]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
794,718,Zygarde50% Forme,Dragon,Ground,600,108,100,121,81,95,95,6,True
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [38]:
import re

In [39]:
df.loc[df['Type 1'].str.contains('fire|grass',regex = True)]

Empty DataFrame
Columns: [#, Name, Type 1, Type 2, Total, HP, Attack, Defense, Sp. Atk, Sp. Def, Speed, Generation, Legendary]
Index: []

In [40]:
df.loc[df['Type 1'].str.contains('fire|grass', flags = re.I ,regex = True)]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
735,667,Litleo,Fire,Normal,369,62,50,58,73,54,72,6,False
736,668,Pyroar,Fire,Normal,507,86,68,72,109,66,106,6,False
740,672,Skiddo,Grass,NaN,350,66,65,48,62,57,52,6,False
741,673,Gogoat,Grass,NaN,531,123,100,62,97,81,68,6,False
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [41]:
df.loc[df['Name'].str.contains('^wa[a-z]*', flags = re.I, regex = True)]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
10,8,Wartortle,Water,NaN,405,59,63,80,65,80,58,1,False
350,320,Wailmer,Water,NaN,400,130,70,35,70,35,60,3,False
351,321,Wailord,Water,NaN,500,170,90,45,90,45,60,3,False
400,365,Walrein,Ice,Water,530,110,80,90,95,90,65,3,False
564,505,Watchog,Normal,NaN,420,60,85,69,60,69,77,5,False

## Conditional Changes

In [42]:
df.loc[df['Type 1'] == 'Fire', 'Type 1'] = 'Flamer'

In [43]:
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Flamer,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Flamer,Water,600,80,110,120,130,90,70,6,True

In [44]:
df.loc[df['Type 1'] == 'Flamer', 'Legendary'] = True
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Flamer,NaN,309,39,52,43,60,50,65,1,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Flamer,Water,600,80,110,120,130,90,70,6,True

In [45]:
df.loc[df['Total'] > 500, ['Generation', 'Legendary']] = ['Test Value', 'Test Value 1']

In [46]:
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,Test Value,Test Value 1
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,Test Value,Test Value 1
4,4,Charmander,Flamer,NaN,309,39,52,43,60,50,65,1,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,Test Value,Test Value 1
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,Test Value,Test Value 1
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,Test Value,Test Value 1
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,Test Value,Test Value 1
799,721,Volcanion,Flamer,Water,600,80,110,120,130,90,70,Test Value,Test Value 1

## Aggregate Statistics - Group by

In [47]:
df.groupby(['Type 1']).mean().sort_values('Defense',ascending = False)

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed
Type 1,,,,,,,,
Steel,442.851852,487.703704,65.222222,92.703704,126.370370,67.518519,80.629630,55.259259
Rock,392.727273,453.750000,65.363636,92.863636,100.795455,63.340909,75.477273,55.909091
Dragon,474.375000,550.531250,83.312500,112.125000,86.375000,96.843750,88.843750,83.031250
Ground,356.281250,437.500000,73.781250,95.750000,84.843750,56.468750,62.750000,63.906250
Ghost,486.500000,439.562500,64.437500,73.781250,81.187500,79.343750,76.468750,64.343750
Water,303.089286,430.455357,72.062500,74.151786,72.946429,74.812500,70.517857,65.964286
Ice,423.541667,433.458333,72.000000,72.750000,71.416667,77.541667,76.291667,63.458333
Grass,344.871429,421.142857,67.271429,73.214286,70.800000,77.500000,70.428571,61.928571
Bug,334.492754,378.927536,56.884058,70.971014,70.724638,53.869565,64.797101,61.681159
Dark,461.354839,445.741935,66.806452,88.387097,70.225806,74.645161,69.516129,76.161290
Poison,251.785714,399.142857,67.250000,74.678571,68.821429,60.428571,64.392857,63.571429
Flamer,327.403846,458.076923,69.903846,84.769231,67.769231,88.980769,72.211538,74.442308
Psychic,380.807018,475.947368,70.631579,71.456140,67.684211,98.403509,86.280702,81.491228
Electric,363.500000,443.409091,59.795455,69.090909,66.295455,90.022727,73.704545,84.500000
Flying,677.750000,485.000000,70.750000,78.750000,66.250000,94.250000,72.500000,102.500000
Fighting,363.851852,416.444444,69.851852,96.777778,65.925926,53.111111,64.703704,66.074074
Fairy,449.529412,413.176471,74.117647,61.529412,65.705882,78.529412,84.705882,48.588235
Normal,319.173469,401.683673,77.275510,73.469388,59.846939,55.816327,63.724490,71.551020

In [48]:
df.groupby(['Type 2']).mean().sort_values('Attack', ascending = False)

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed
Type 2,,,,,,,,
Fighting,438.192308,525.846154,79.461538,112.846154,82.500000,81.269231,82.384615,87.384615
Dark,413.850000,484.400000,75.550000,109.800000,72.050000,81.800000,69.850000,75.350000
Ice,441.285714,525.714286,90.000000,98.000000,85.642857,92.642857,84.785714,74.642857
Dragon,482.555556,526.166667,82.166667,94.444444,87.055556,98.500000,83.444444,80.555556
Steel,435.636364,485.227273,64.636364,92.590909,104.636364,77.727273,86.272727,59.363636
Bug,382.000000,393.333333,53.333333,90.000000,80.000000,46.666667,61.666667,61.666667
Ground,307.600000,444.342857,77.228571,89.857143,90.314286,65.542857,66.742857,54.657143
Ghost,551.714286,430.714286,59.142857,84.142857,82.285714,73.214286,78.071429,53.857143
Rock,347.785714,434.642857,68.071429,84.000000,126.857143,51.142857,68.571429,36.000000
Fire,481.833333,506.250000,71.250000,81.250000,80.166667,110.416667,83.500000,79.666667
Flying,331.103093,452.546392,71.391753,80.288660,68.309278,75.628866,71.206186,85.721649
Psychic,337.151515,479.060606,72.212121,74.696970,87.030303,88.030303,87.606061,69.484848
Grass,505.400000,408.920000,62.640000,74.160000,80.120000,60.160000,74.520000,57.320000
Electric,465.666667,455.333333,88.166667,72.666667,68.333333,81.166667,73.500000,71.500000
Water,400.000000,418.214286,62.714286,70.142857,85.071429,74.500000,68.642857,57.142857
Poison,169.970588,396.500000,58.764706,67.588235,59.558824,74.029412,69.911765,66.647059
Fairy,379.043478,417.956522,64.304348,61.608696,73.869565,75.000000,81.956522,61.217391
Normal,681.000000,411.500000,63.500000,52.750000,53.750000,88.000000,64.250000,89.250000

In [49]:
df.groupby(['Type 1']).sum()

              #  Total    HP  Attack  Defense  Sp. Atk  Sp. Def  Speed
Type 1
Bug       23080  26146  3925    4897     4880     3717     4471   4256
Dark      14302  13818  2071    2740     2177     2314     2155   2361
Dragon    15180  17617  2666    3588     2764     3099     2843   2657
Electric  15994  19510  2631    3040     2917     3961     3243   3718
Fairy      7642   7024  1260    1046     1117     1335     1440    826
Fighting   9824  11244  1886    2613     1780     1434     1747   1784
Flamer    17025  23820  3635    4408     3524     4627     3755   3871
Flying     2711   1940   283     315      265      377      290    410
Ghost     15568  14066  2062    2361     2598     2539     2447   2059
Grass     24141  29480  4709    5125     4956     5425     4930   4335
Ground    11401  14000  2361    3064     2715     1807     2008   2045
Ice       10165  10403  1728    1746     1714     1861     1831   1523
Normal    31279  39365  7573    7200     5865     5470     6245   7012
Poison     7050  11176  1883    2091     1927     1692     1803   1780
Psychic   21706  27129  4026    4073     3858     5609     4918   4645
Rock      17280  19965  2876    4086     4435     2787     3321   2460
Steel     11957  13168  1761    2503     3412     1823     2177   1492
Water     33946  48211  8071    8305     8170     8379     7898   7388

In [50]:
df['count']=1
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,count
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,1
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,1
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,Test Value,Test Value 1,1
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,Test Value,Test Value 1,1
4,4,Charmander,Flamer,NaN,309,39,52,43,60,50,65,1,True,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,Test Value,Test Value 1,1
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,Test Value,Test Value 1,1
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,Test Value,Test Value 1,1
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,Test Value,Test Value 1,1
799,721,Volcanion,Flamer,Water,600,80,110,120,130,90,70,Test Value,Test Value 1,1

In [51]:
 df.groupby(['Type 1', 'Type 2']).count()['count']

Type 1  Type 2
Bug     Electric     2
        Fighting     2
        Fire         2
        Flying      14
        Ghost        1
                    ..
Water   Ice          3
        Poison       3
        Psychic      5
        Rock         4
        Steel        1
Name: count, Length: 136, dtype: int64

In [52]:
 df.groupby(['Type 1']).count()['count']

Type 1
Bug          69
Dark         31
Dragon       32
Electric     44
Fairy        17
Fighting     27
Flamer       52
Flying        4
Ghost        32
Grass        70
Ground       32
Ice          24
Normal       98
Poison       28
Psychic      57
Rock         44
Steel        27
Water       112
Name: count, dtype: int64

## Working with large amounts of Data

In [58]:
for df in pd.read_csv('modified_pokemon.csv', chunksize = 300):
    print('Chunk DF')
    print(df)

Chunk DF
       #                   Name  Type 1  Type 2  Total  HP  Attack  Defense  \
0      1              Bulbasaur   Grass  Poison    318  45      49       49
1      2                Ivysaur   Grass  Poison    405  60      62       63
2      3               Venusaur   Grass  Poison    525  80      82       83
3      3  VenusaurMega Venusaur   Grass  Poison    625  80     100      123
4      4             Charmander    Fire     NaN    309  39      52       43
..   ...                    ...     ...     ...    ...  ..     ...      ...
295  272               Ludicolo   Water   Grass    480  80      70       70
296  273                 Seedot   Grass     NaN    220  40      40       50
297  274                Nuzleaf   Grass    Dark    340  70      70       40
298  275                Shiftry   Grass    Dark    480  90     100       60
299  276                Taillow  Normal  Flying    270  40      55       30

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
0         65       65     45           1      False
1         80       80     60           1      False
2        100      100     80           1      False
3        122      120     80           1      False
4         60       50     65           1      False
..       ...      ...    ...         ...        ...
295       90      100     70           3      False
296       30       30     30           3      False
297       60       40     60           3      False
298       90       60     80           3      False
299       30       30     85           3      False

[300 rows x 13 columns]
Chunk DF
       #        Name    Type 1  Type 2  Total   HP  Attack  Defense  Sp. Atk  \
300  277     Swellow    Normal  Flying    430   60      85       60       50
301  278     Wingull     Water  Flying    270   40      30       30       55
302  279    Pelipper     Water  Flying    430   60      50      100       85
303  280       Ralts   Psychic   Fairy    198   28      25       25       45
304  281      Kirlia   Psychic   Fairy    278   38      35       35       65
..   ...         ...       ...     ...    ...  ...     ...      ...      ...
595  535     Tympole     Water     NaN    294   50      50       40       50
596  536   Palpitoad     Water  Ground    384   75      65       55       65
597  537  Seismitoad     Water  Ground    509  105      95       75       85
598  538       Throh  Fighting     NaN    465  120     100       85       30
599  539        Sawk  Fighting     NaN    465   75     125       75       30

     Sp. Def  Speed  Generation  Legendary
300       50    125           3      False
301       30     85           3      False
302       70     65           3      False
303       35     40           3      False
304       55     50           3      False
..       ...    ...         ...        ...
595       40     64           5      False
596       55     69           5      False
597       75     74           5      False
598       85     45           5      False
599       75     85           5      False

[300 rows x 13 columns]
Chunk DF
       #                 Name   Type 1  Type 2  Total  HP  Attack  Defense  \
600  540             Sewaddle      Bug   Grass    310  45      53       70
601  541             Swadloon      Bug   Grass    380  55      63       90
602  542             Leavanny      Bug   Grass    500  75     103       80
603  543             Venipede      Bug  Poison    260  30      45       59
604  544           Whirlipede      Bug  Poison    360  40      55       99
..   ...                  ...      ...     ...    ...  ..     ...      ...
795  719              Diancie     Rock   Fairy    600  50     100      150
796  719  DiancieMega Diancie     Rock   Fairy    700  50     160      110
797  720  HoopaHoopa Confined  Psychic   Ghost    600  80     110       60
798  720   HoopaHoopa Unbound  Psychic    Dark    680  80     160       60
799  721            Volcanion     Fire   Water    600  80     110      120

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
600       40       60     42           5      False
601       50       80     42           5      False
602       70       80     92           5      False
603       30       39     57           5      False
604       40       79     47           5      False
..       ...      ...    ...         ...        ...
795      100      150     50           6       True
796      160      110    110           6       True
797      150      130     70           6       True
798      170      130     80           6       True
799      130       90     70           6       True

[200 rows x 13 columns]

In [59]:
new_df = pd.DataFrame(columns = df.columns)

for df in pd.read_csv('modified_pokemon.csv', chunksize = 300):
    results= df.groupby(['Type 1']).count() 
    
    new_df = pd.concat([new_df, results])
    print(new_df)

           # Name Type 1 Type 2 Total  HP Attack Defense Sp. Atk Sp. Def  \
Bug       31   31    NaN     24    31  31     31      31      31      31
Dark       8    8    NaN      5     8   8      8       8       8       8
Dragon     3    3    NaN      1     3   3      3       3       3       3
Electric  16   16    NaN      4    16  16     16      16      16      16
Fairy      7    7    NaN      1     7   7      7       7       7       7
Fighting   9    9    NaN      0     9   9      9       9       9       9
Fire      26   26    NaN      9    26  26     26      26      26      26
Ghost      5    5    NaN      4     5   5      5       5       5       5
Grass     29   29    NaN     18    29  29     29      29      29      29
Ground    11   11    NaN      3    11  11     11      11      11      11
Ice        6    6    NaN      6     6   6      6       6       6       6
Normal    42   42    NaN     16    42  42     42      42      42      42
Poison    15   15    NaN      5    15  15     15      15      15      15
Psychic   18   18    NaN      6    18  18     18      18      18      18
Rock      15   15    NaN     14    15  15     15      15      15      15
Steel      3    3    NaN      3     3   3      3       3       3       3
Water     56   56    NaN     29    56  56     56      56      56      56

         Speed Generation Legendary
Bug         31         31        31
Dark         8          8         8
Dragon       3          3         3
Electric    16         16        16
Fairy        7          7         7
Fighting     9          9         9
Fire        26         26        26
Ghost        5          5         5
Grass       29         29        29
Ground      11         11        11
Ice          6          6         6
Normal      42         42        42
Poison      15         15        15
Psychic     18         18        18
Rock        15         15        15
Steel        3          3         3
Water       56         56        56
           # Name Type 1 Type 2 Total  HP Attack Defense Sp. Atk Sp. Def  \
Bug       31   31    NaN     24    31  31     31      31      31      31
Dark       8    8    NaN      5     8   8      8       8       8       8
Dragon     3    3    NaN      1     3   3      3       3       3       3
Electric  16   16    NaN      4    16  16     16      16      16      16
Fairy      7    7    NaN      1     7   7      7       7       7       7
Fighting   9    9    NaN      0     9   9      9       9       9       9
Fire      26   26    NaN      9    26  26     26      26      26      26
Ghost      5    5    NaN      4     5   5      5       5       5       5
Grass     29   29    NaN     18    29  29     29      29      29      29
Ground    11   11    NaN      3    11  11     11      11      11      11
Ice        6    6    NaN      6     6   6      6       6       6       6
Normal    42   42    NaN     16    42  42     42      42      42      42
Poison    15   15    NaN      5    15  15     15      15      15      15
Psychic   18   18    NaN      6    18  18     18      18      18      18
Rock      15   15    NaN     14    15  15     15      15      15      15
Steel      3    3    NaN      3     3   3      3       3       3       3
Water     56   56    NaN     29    56  56     56      56      56      56
Bug       17   17    NaN     12    17  17     17      17      17      17
Dark       9    9    NaN      4     9   9      9       9       9       9
Dragon    16   16    NaN     14    16  16     16      16      16      16
Electric  19   19    NaN      7    19  19     19      19      19      19
Fairy      1    1    NaN      1     1   1      1       1       1       1
Fighting  13   13    NaN      5    13  13     13      13      13      13
Fire      14   14    NaN      8    14  14     14      14      14      14
Ghost     12   12    NaN      5    12  12     12      12      12      12
Grass     26   26    NaN     11    26  26     26      26      26      26
Ground    13   13    NaN      8    13  13     13      13      13      13
Ice       10   10    NaN      5    10  10     10      10      10      10
Normal    43   43    NaN     13    43  43     43      43      43      43
Poison     9    9    NaN      6     9   9      9       9       9       9
Psychic   25   25    NaN     10    25  25     25      25      25      25
Rock      17   17    NaN      9    17  17     17      17      17      17
Steel     15   15    NaN     13    15  15     15      15      15      15
Water     41   41    NaN     15    41  41     41      41      41      41

         Speed Generation Legendary
Bug         31         31        31
Dark         8          8         8
Dragon       3          3         3
Electric    16         16        16
Fairy        7          7         7
Fighting     9          9         9
Fire        26         26        26
Ghost        5          5         5
Grass       29         29        29
Ground      11         11        11
Ice          6          6         6
Normal      42         42        42
Poison      15         15        15
Psychic     18         18        18
Rock        15         15        15
Steel        3          3         3
Water       56         56        56
Bug         17         17        17
Dark         9          9         9
Dragon      16         16        16
Electric    19         19        19
Fairy        1          1         1
Fighting    13         13        13
Fire        14         14        14
Ghost       12         12        12
Grass       26         26        26
Ground      13         13        13
Ice         10         10        10
Normal      43         43        43
Poison       9          9         9
Psychic     25         25        25
Rock        17         17        17
Steel       15         15        15
Water       41         41        41
           # Name Type 1 Type 2 Total  HP Attack Defense Sp. Atk Sp. Def  \
Bug       31   31    NaN     24    31  31     31      31      31      31
Dark       8    8    NaN      5     8   8      8       8       8       8
Dragon     3    3    NaN      1     3   3      3       3       3       3
Electric  16   16    NaN      4    16  16     16      16      16      16
Fairy      7    7    NaN      1     7   7      7       7       7       7
Fighting   9    9    NaN      0     9   9      9       9       9       9
Fire      26   26    NaN      9    26  26     26      26      26      26
Ghost      5    5    NaN      4     5   5      5       5       5       5
Grass     29   29    NaN     18    29  29     29      29      29      29
Ground    11   11    NaN      3    11  11     11      11      11      11
Ice        6    6    NaN      6     6   6      6       6       6       6
Normal    42   42    NaN     16    42  42     42      42      42      42
Poison    15   15    NaN      5    15  15     15      15      15      15
Psychic   18   18    NaN      6    18  18     18      18      18      18
Rock      15   15    NaN     14    15  15     15      15      15      15
Steel      3    3    NaN      3     3   3      3       3       3       3
Water     56   56    NaN     29    56  56     56      56      56      56
Bug       17   17    NaN     12    17  17     17      17      17      17
Dark       9    9    NaN      4     9   9      9       9       9       9
Dragon    16   16    NaN     14    16  16     16      16      16      16
Electric  19   19    NaN      7    19  19     19      19      19      19
Fairy      1    1    NaN      1     1   1      1       1       1       1
Fighting  13   13    NaN      5    13  13     13      13      13      13
Fire      14   14    NaN      8    14  14     14      14      14      14
Ghost     12   12    NaN      5    12  12     12      12      12      12
Grass     26   26    NaN     11    26  26     26      26      26      26
Ground    13   13    NaN      8    13  13     13      13      13      13
Ice       10   10    NaN      5    10  10     10      10      10      10
Normal    43   43    NaN     13    43  43     43      43      43      43
Poison     9    9    NaN      6     9   9      9       9       9       9
Psychic   25   25    NaN     10    25  25     25      25      25      25
Rock      17   17    NaN      9    17  17     17      17      17      17
Steel     15   15    NaN     13    15  15     15      15      15      15
Water     41   41    NaN     15    41  41     41      41      41      41
Bug       21   21    NaN     16    21  21     21      21      21      21
Dark      14   14    NaN     12    14  14     14      14      14      14
Dragon    13   13    NaN      6    13  13     13      13      13      13
Electric   9    9    NaN      6     9   9      9       9       9       9
Fairy      9    9    NaN      0     9   9      9       9       9       9
Fighting   5    5    NaN      2     5   5      5       5       5       5
Fire      12   12    NaN      7    12  12     12      12      12      12
Flying     4    4    NaN      2     4   4      4       4       4       4
Ghost     15   15    NaN     13    15  15     15      15      15      15
Grass     15   15    NaN      8    15  15     15      15      15      15
Ground     8    8    NaN      8     8   8      8       8       8       8
Ice        8    8    NaN      0     8   8      8       8       8       8
Normal    13   13    NaN      8    13  13     13      13      13      13
Poison     4    4    NaN      2     4   4      4       4       4       4
Psychic   14   14    NaN      3    14  14     14      14      14      14
Rock      12   12    NaN     12    12  12     12      12      12      12
Steel      9    9    NaN      6     9   9      9       9       9       9
Water     15   15    NaN      9    15  15     15      15      15      15

         Speed Generation Legendary
Bug         31         31        31
Dark         8          8         8
Dragon       3          3         3
Electric    16         16        16
Fairy        7          7         7
Fighting     9          9         9
Fire        26         26        26
Ghost        5          5         5
Grass       29         29        29
Ground      11         11        11
Ice          6          6         6
Normal      42         42        42
Poison      15         15        15
Psychic     18         18        18
Rock        15         15        15
Steel        3          3         3
Water       56         56        56
Bug         17         17        17
Dark         9          9         9
Dragon      16         16        16
Electric    19         19        19
Fairy        1          1         1
Fighting    13         13        13
Fire        14         14        14
Ghost       12         12        12
Grass       26         26        26
Ground      13         13        13
Ice         10         10        10
Normal      43         43        43
Poison       9          9         9
Psychic     25         25        25
Rock        17         17        17
Steel       15         15        15
Water       41         41        41
Bug         21         21        21
Dark        14         14        14
Dragon      13         13        13
Electric     9          9         9
Fairy        9          9         9
Fighting     5          5         5
Fire        12         12        12
Flying       4          4         4
Ghost       15         15        15
Grass       15         15        15
Ground       8          8         8
Ice          8          8         8
Normal      13         13        13
Poison       4          4         4
Psychic     14         14        14
Rock        12         12        12
Steel        9          9         9
Water       15         15        15